[package]
name = "sbt-client"
version = "0.1.1"
authors = ["Chris Birchall <chris.birchall@gmail.com>"]

[dependencies]
regex = "1"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
ansi_term = "0.11"
